package twemojichat.buildlogic

data class VersionLine(
    val projectName: String,
    val sourceSetDirectory: String?,
    val loaders: Set<LoaderKind>,
    val minecraftVersion: String,
    val minecraftVersionRange: String,
    val javaVersion: Int,
    val fabricLoaderVersion: String,
    val fabricApiVersion: String,
    val fabricPluginId: String,
    val neoVersion: String,
    val neoVersionRange: String,
    val loaderVersionRange: String,
    val usesLegacyForge: Boolean
)

enum class LoaderKind {
    FABRIC,
    FORGE,
    NEOFORGE
}

val SUPPORTED_VERSION_LINES = listOf(
    VersionLine(
        projectName = "1_20_1",
        sourceSetDirectory = "1201",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.FORGE),
        minecraftVersion = "1.20.1",
        minecraftVersionRange = "[1.20.1,1.21)",
        javaVersion = 17,
        fabricLoaderVersion = "0.16.14",
        fabricApiVersion = "0.92.9+1.20.1",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "1.20.1-47.4.0",
        neoVersionRange = "[47.4,)",
        loaderVersionRange = "[47,)",
        usesLegacyForge = true
    ),
    VersionLine(
        projectName = "1_20_2",
        sourceSetDirectory = "1201",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.FORGE),
        minecraftVersion = "1.20.2",
        minecraftVersionRange = "[1.20.2,1.21)",
        javaVersion = 17,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.91.6+1.20.2",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "1.20.2-48.1.0",
        neoVersionRange = "[48.1,)",
        loaderVersionRange = "[48,)",
        usesLegacyForge = true
    ),
    VersionLine(
        projectName = "1_20_3",
        sourceSetDirectory = "1201",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.FORGE),
        minecraftVersion = "1.20.3",
        minecraftVersionRange = "[1.20.3,1.21)",
        javaVersion = 17,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.91.1+1.20.3",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "1.20.3-49.0.2",
        neoVersionRange = "[49.0,)",
        loaderVersionRange = "[49,)",
        usesLegacyForge = true
    ),
    VersionLine(
        projectName = "1_20_4",
        sourceSetDirectory = "1201",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.FORGE),
        minecraftVersion = "1.20.4",
        minecraftVersionRange = "[1.20.4,1.21)",
        javaVersion = 17,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.97.3+1.20.4",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "1.20.4-49.2.7",
        neoVersionRange = "[49.2,)",
        loaderVersionRange = "[49,)",
        usesLegacyForge = true
    ),
    VersionLine(
        projectName = "1_20_5",
        sourceSetDirectory = "1205",
        loaders = setOf(LoaderKind.FABRIC),
        minecraftVersion = "1.20.5",
        minecraftVersionRange = "[1.20.5,1.21)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.97.8+1.20.5",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "20.5.21-beta",
        neoVersionRange = "[20.5,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_20_6",
        sourceSetDirectory = "1205",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.20.6",
        minecraftVersionRange = "[1.20.6,1.21)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.100.8+1.20.6",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "20.6.139",
        neoVersionRange = "[20.6,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_21",
        sourceSetDirectory = "1211",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.21",
        minecraftVersionRange = "[1.21,1.22)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.102.0+1.21",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "21.0.167",
        neoVersionRange = "[21.0,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_21_1",
        sourceSetDirectory = "1211",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.21.1",
        minecraftVersionRange = "[1.21.1,1.22)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.116.12+1.21.1",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "21.1.233",
        neoVersionRange = "[21.1,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_21_2",
        sourceSetDirectory = "1211",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.21.2",
        minecraftVersionRange = "[1.21.2,1.22)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.106.1+1.21.2",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "21.2.1-beta",
        neoVersionRange = "[21.2,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_21_3",
        sourceSetDirectory = "1211",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.21.3",
        minecraftVersionRange = "[1.21.3,1.22)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.114.1+1.21.3",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "21.3.96",
        neoVersionRange = "[21.3,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_21_4",
        sourceSetDirectory = "1211",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.21.4",
        minecraftVersionRange = "[1.21.4,1.22)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.119.4+1.21.4",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "21.4.157",
        neoVersionRange = "[21.4,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_21_5",
        sourceSetDirectory = "1211",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.21.5",
        minecraftVersionRange = "[1.21.5,1.22)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.128.2+1.21.5",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "21.5.97",
        neoVersionRange = "[21.5,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_21_6",
        sourceSetDirectory = "1211",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.21.6",
        minecraftVersionRange = "[1.21.6,1.22)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.128.2+1.21.6",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "21.6.20-beta",
        neoVersionRange = "[21.6,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_21_7",
        sourceSetDirectory = "1211",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.21.7",
        minecraftVersionRange = "[1.21.7,1.22)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.129.0+1.21.7",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "21.7.25-beta",
        neoVersionRange = "[21.7,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_21_8",
        sourceSetDirectory = "1211",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.21.8",
        minecraftVersionRange = "[1.21.8,1.22)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.136.1+1.21.8",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "21.8.53",
        neoVersionRange = "[21.8,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_21_9",
        sourceSetDirectory = "1212",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.21.9",
        minecraftVersionRange = "[1.21.9,1.22)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.134.1+1.21.9",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "21.9.16-beta",
        neoVersionRange = "[21.9,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_21_10",
        sourceSetDirectory = "1212",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.21.10",
        minecraftVersionRange = "[1.21.10,1.22)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.138.4+1.21.10",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "21.10.64",
        neoVersionRange = "[21.10,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "1_21_11",
        sourceSetDirectory = "12111",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "1.21.11",
        minecraftVersionRange = "[1.21.11,1.22)",
        javaVersion = 21,
        fabricLoaderVersion = "0.19.3",
        fabricApiVersion = "0.141.4+1.21.11",
        fabricPluginId = "net.fabricmc.fabric-loom-remap",
        neoVersion = "21.11.42",
        neoVersionRange = "[21.11,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    ),
    VersionLine(
        projectName = "26_1",
        sourceSetDirectory = "261",
        loaders = setOf(LoaderKind.FABRIC, LoaderKind.NEOFORGE),
        minecraftVersion = "26.1.2",
        minecraftVersionRange = "[26.1,26.2)",
        javaVersion = 25,
        fabricLoaderVersion = "0.19.2",
        fabricApiVersion = "0.150.0+26.1.2",
        fabricPluginId = "net.fabricmc.fabric-loom",
        neoVersion = "26.1.2.72",
        neoVersionRange = "[26.1,)",
        loaderVersionRange = "[4,)",
        usesLegacyForge = false
    )
)

val SUPPORTED_VERSION_LINE_MAP = SUPPORTED_VERSION_LINES.associateBy(VersionLine::projectName)

fun versionLine(projectName: String): VersionLine = SUPPORTED_VERSION_LINE_MAP.getValue(projectName)
